# Generated by Django 3.2 on 2021-04-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books_Authors',
        ),
    ]
