# Generated by Django 3.2 on 2021-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books', '0004_remove_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='this is stuff about this book'),
            preserve_default=False,
        ),
    ]
