# Generated by Django 3.2 on 2021-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull_tv_shows', '0002_alter_show_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release',
            field=models.DateField(null=True),
        ),
    ]
